# Generated by Django 6.0.3 on 2026-03-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementFamilial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_evt', models.CharField(choices=[('MARIAGE', 'Mariage'), ('BAPTEME', 'Baptême'), ('REUNION', 'Réunion de famille'), ('GRADUATION', 'Diplôme / Succès'), ('FIANCAILLES', 'Vodiondry / soratra'), ('FUNEBRE', 'Decès'), ('AUTRE', 'Autre')], max_length=20)),
                ('date_evenement', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('lieu', models.CharField(blank=True, max_length=255)),
                ('participants', models.ManyToManyField(related_name='evenements_lies', to='genealogy.personne')),
            ],
            options={
                'verbose_name': 'Événement',
                'ordering': ['date_evenement'],
            },
        ),
    ]
