# Generated by Django 6.0.3 on 2026-03-28 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementfamilial',
            name='est_valide',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evenementfamilial',
            name='organisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements_crees', to=settings.AUTH_USER_MODEL),
        ),
    ]
