# Generated by Django 6.0.3 on 2026-03-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_commentaire_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenementfamilial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events/images/'),
        ),
    ]
