# Generated by Django 6.0.3 on 2026-03-28 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genealogy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personne', models.OneToOneField(blank=True, help_text="Liez cet utilisateur à sa fiche dans l'arbre généalogique.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compte_utilisateur', to='genealogy.personne')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
