# Generated by Django 6.0.3 on 2026-03-27 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('surnom', models.CharField(blank=True, max_length=100)),
                ('genre', models.CharField(choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('est_en_vie', models.BooleanField(default=True, verbose_name='Est en vie ?')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField(blank=True, help_text='Laisser vide si en vie', null=True)),
                ('cause_deces', models.CharField(blank=True, max_length=255)),
                ('signes_distinctifs', models.TextField(blank=True, help_text='Ex: Cicatrice joue droite, chauve, etc.')),
                ('biographie', models.TextField(blank=True)),
                ('photo_profil', models.ImageField(blank=True, upload_to='photos/profils/')),
                ('cv_pdf', models.FileField(blank=True, upload_to='cv/')),
                ('video_presentation', models.FileField(blank=True, upload_to='videos/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('facebook_url', models.URLField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('etudes', models.CharField(blank=True, max_length=200)),
                ('localisation_actuelle', models.CharField(blank=True, max_length=200)),
                ('mere_adoptif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_adopt_mere', to='genealogy.personne')),
                ('mere_bio', models.ForeignKey(blank=True, limit_choices_to={'genre': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_bio_mere', to='genealogy.personne')),
                ('pere_adoptif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_adopt_pere', to='genealogy.personne')),
                ('pere_bio', models.ForeignKey(blank=True, limit_choices_to={'genre': 'H'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_bio_pere', to='genealogy.personne')),
            ],
        ),
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('EN_COUPLE', 'En couple'), ('FIANCE', 'Fiancés'), ('MARIE', 'Mariés'), ('DIVORCE', 'Divorcés'), ('VEUF', 'Veuf/Veuve')], default='EN_COUPLE', max_length=20)),
                ('date_union', models.DateField(blank=True, null=True)),
                ('date_separation', models.DateField(blank=True, null=True)),
                ('femme', models.ForeignKey(limit_choices_to={'genre': 'F'}, on_delete=django.db.models.deletion.CASCADE, related_name='unions_f', to='genealogy.personne')),
                ('homme', models.ForeignKey(limit_choices_to={'genre': 'H'}, on_delete=django.db.models.deletion.CASCADE, related_name='unions_h', to='genealogy.personne')),
            ],
        ),
    ]
