# Generated by Django 6.0.3 on 2026-03-28 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genealogy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('type_media', models.CharField(choices=[('IMAGE', 'Image / Photo'), ('VIDEO', 'Vidéo')], default='IMAGE', max_length=10)),
                ('fichier', models.FileField(upload_to='gallery/%Y/%m/')),
                ('date_prise_vue', models.DateField(blank=True, help_text='Quand cette photo/vidéo a-t-il été prise ?', null=True)),
                ('est_prive', models.BooleanField(default=False, help_text='Cocher pour que seul le cercle proche puisse voir.')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='genealogy.personne')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Galerie Multimédia',
                'ordering': ['-date_prise_vue', '-date_ajout'],
            },
        ),
    ]
