# Generated by Django 6.0.3 on 2026-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_notif',
            field=models.CharField(choices=[('ANNIVERSAIRE', 'Anniversaire de naissance'), ('DECES', 'Commémoration de décès'), ('EVENEMENT', 'Événement familial'), ('COMMENTAIRE', 'Commentaire'), ('REACTION', 'Réaction'), ('SYSTEME', 'Message système')], max_length=20),
        ),
    ]
